before_script:
  - ruby -v
  - which ruby
  - bundle install --jobs $(nproc)  "${FLAGS[@]}" --path ~/gems/aisler_pricing

stages:
  - test
  - deploy


rspec_job:
  stage: test
  script:
    - bundle exec rspec

deploy_job:
  only:
    - master
  stage: deploy
  script:
    - bundle exec rake build
    - bundle exec gem inabox -g https://gems.aisler.team

