before_script:
  - bundle version
  - bundle config jobs $(nproc)
  - bundle config path vendor/bundle
  - bundle config clean true
  - bundle install

.cache:
    key: default-cache
    paths:
      - vendor/bundle

stages:
  - test
  - deploy

rspec_3_2:
  image: ruby:3.2
  tags:
    - docker
  stage: test
  script:
    - bin/rspec
  extends:
    - .cache

rspec_2_7:
  image: ruby:2.7
  tags:
    - docker
  stage: test
  script:
    - bin/rspec
  extends:
    - .cache

deploy_job:
  image: ruby:3.2
  tags:
    - docker
  stage: deploy
  only:
    - master
  script:
    - bin/rake build
    - bundle exec gem inabox -g https://${BUNDLE_GEMS__AISLER__TEAM}@gems.aisler.team
  extends:
    - .cache
