before_script:
  - ruby -v
  - which ruby
  - bundle install --jobs $(nproc)  "${FLAGS[@]}"

stages:
  - test
  - deploy


rspec_job:
  stage: test
  script:
    - bundle exec rspec

deploy_job:
  stage: deploy
  script:
    - bundle exec rake build
    - bundle exec gem inabox -g https://aisler:$GEM_SERVER_PASSWORD@gems.aisler.team

