before_script:
  - bundle install --jobs $(nproc) --path .gems "${FLAGS[@]}"

cache:
    key: default-cache
    paths:
      - .gems

stages:
  - test
  - deploy

rspec_job:
  image: ruby:2.5.1
  tags:
    - docker
  stage: test
  script:
    - bin/rspec

deploy_job:
  image: ruby:2.5.1
  tags:
    - docker
  stage: deploy
  only:
    - master
  script:
    - bin/rake build
    - bundle exec gem inabox -g https://${BUNDLE_GEMS__AISLER__TEAM}@gems.aisler.team
